spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inksoul_dev
    username: inksoul_dev
    password: dev123
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    
logging:
  level:
    com.inksoul: DEBUG
    org.springframework.web: DEBUG